fix(release): implement semantic versioning
- Add versioning job to the CI workflow for automatic version
  updates and changelog generation.
- Integrate python-semantic-release for managing versioning
  and changelog updates.
- Update dependencies in pyproject.toml and uv.lock to
  include python-semantic-release.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -13,6 +13,46 @@ on:
 
 
 jobs:
+  versioning:
+    runs-on: ubuntu-latest
+
+    steps:
+    - uses: actions/checkout@v4
+      with:
+        persist-credentials: true
+
+    - name: Install uv
+      uses: astral-sh/setup-uv@v6
+      with:
+        version: "0.8.9"
+
+    - name: Install Dependencies
+      run: |
+        uv python install
+        uv sync --group versioning
+
+    - name: Update Version and Changelog
+      run: |
+        rm -f CHANGELOG.md
+        uv run --frozen --no-sync poe version-bump
+
+        differences=$(git diff | xargs)
+
+        if [ -z "$differences" ]; then
+          echo "No changes needed"
+          exit 0
+        fi
+
+        echo "::error::The version and/or Changelog is outdated"
+        echo "$differences"
+
+        git add --all
+        git commit -m "chore(release): bump version and update changelog"
+        git push
+
+        sleep 30
+        exit 1
+
   lint:
     runs-on: ubuntu-latest
 
